Go version >= 1.17
samba-in-kubernetes/samba-operator pull request #253
Opened 2022-09-20 11:23 UTC by synarete

Set minimal supported version of Go to 1.17. Updated github workflow accordingly.

Prefer 1.17 over 1.18 as some of our auxiliary build tools (linters) are still buggy when used with go1.18 features (namely, generics).

2022-09-20 14:15 UTC, synarete commented
> Everything looks good with one minor caveat - the list of packages in go.mod looks longer that I expected (I expected new stuff in that 2nd section, but not that much). Can you please verify you ran `go mod tidy`? If so, I'll happily approve - I just want to double check the list isn't longer than necessary.

I re-run `go mod tidy` and got same result, both with `go1.17` and `go1.18`. May need to do deeper dive into https://go.dev/ref/mod#go-mod-file-require but I would prefer to do so in a separate PR.

2022-09-20 14:20 UTC, phlogistonjohn approved these changes
LGTM

2022-09-20 14:21 UTC, phlogistonjohn commented
I'll wait approx. one day before merging for other feedback. I will ignore the centos ci status for this PR and merge w/o waiting for success from that CI.

2022-09-21 06:33 UTC, anoopcs9 requested changes
Few changes from this PR already exists as separate PRs(see below comments). I prefer to consider those older PRs and accordingly modify the current one.

2022-09-21 06:33 UTC, anoopcs9 commented on tests/integration/path_permissions.go
> +//go:build integration
#243 includes this change.

2022-09-21 06:33 UTC, anoopcs9 commented on tests/integration/resource_update_test.go
> +
#243 includes this change.

2022-09-21 06:33 UTC, anoopcs9 commented on internal/planner/configuration.go
> +		globals := smbcc.NewGlobals(globalOptions)
This is same as #247 , right?

2022-09-22 14:35 UTC, phlogistonjohn approved these changes
LGTM, thanks.

2022-09-22 14:56 UTC, anoopcs9 commented
/test centos-ci/sink-clustered/mini-k8s-1.24

2022-09-22 15:05 UTC, anoopcs9 approved these changes
lgtm.

2022-09-22 15:39 UTC, merged