go.mod: upgrade to newer versions
samba-in-kubernetes/samba-operator pull request #307
Opened 2023-05-17 12:01 UTC by synarete

Upgrade logr, client-go and controller-runtime to newer versions which include various bug fixes. Align code with respect to changes in those libraries.

2023-05-17 13:56 UTC, phlogistonjohn commented
Thanks!  This has been on my TODO list for a while so I'm happy to see this happen.
On quick skim most things look OK, but since it is a big commit I will need a bit more time to fully review.

2023-05-18 14:33 UTC, phlogistonjohn commented
Commit message nitpick: change `upgrade to newer versions` to `update packages to newer versions`. That way we're clarify that it's not a bump of the required go version, but impacts the dependencies.

2023-05-18 14:39 UTC, phlogistonjohn requested changes
A nitpick, nothing major

2023-05-18 14:39 UTC, phlogistonjohn commented on internal/resources/util_fakes_test.go
> +type fakeSubResource struct{}
Could you move this to directly above the methods? I think Go is OK with that and I was initially confused as to how fakeSubResource could meet the SubResourceClient interface until I scrolled much further down.

2023-06-15 18:07 UTC, phlogistonjohn approved these changes
LGTM. Never hesitate to ping me if I ask for something and then you don't hear back from me for a while. :-)

2023-06-15 18:09 UTC, phlogistonjohn commented
@obnoxxx  @spuiuk 2nd review please?

2023-06-20 09:04 UTC, anoopcs9 approved these changes

2023-06-20 09:35 UTC, anoopcs9 commented
@Mergifyio rebase

2023-06-20 10:19 UTC, merged