config: restrict deployments to amd64 nodes
samba-in-kubernetes/samba-operator pull request #328
Opened 2024-02-13 07:21 UTC by synarete

Until samba-operator supports other architectures (namely, ARM64), restrict its deployment to AMD64 nodes (e.g., in cases of non x86_64 or mixed ARCH clusters) via standard K8s node-selector mechanism [1].

[1] https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

2024-02-13 14:04 UTC, obnoxxx requested changes
@synarete  could you please add a Co-authored tag instead of your signoff to the commit message? I. E. `Co-authored-by: Shachar Sharon <your email>` 

otherwise, this looks like a clean wrapping of PR #326

2024-02-13 14:07 UTC, obnoxxx commented
@phlogistonjohn  wrote.
> It might be nice to clarify that your patch is an adaptation of the original contribution. Something like adding a 'Original-Version-By:' footer?

Not sure it is required because  the original contributor @tiferrei  of #326  is still t author of this PR's  commit which also carries their signoff line

2024-02-13 14:11 UTC, synarete commented
> @synarete could you please add a Co-authored tag instead of your signoff to the commit message? I. E. `Co-authored-by: Shachar Sharon <your email>`
> 
> otherwise, this looks like a clean wrapping of PR #326

ACK

2024-02-13 18:25 UTC, phlogistonjohn approved these changes
good enough for me.

2024-02-14 07:00 UTC, anoopcs9 commented
/retest centos-ci/sink-clustered/mini-k8s-latest

2024-02-14 09:04 UTC, merged