Kubernetes level CI test including AD
samba-in-kubernetes/samba-operator pull request #43
Opened 2021-03-18 23:01 UTC by obnoxxx

based on #42

2021-03-21 22:27 UTC, obnoxxx commented
The ci check fails because the the dc can't be found when trying to join in the init container.
Manually putting a section for the domain into the coredns configmap works, but I couldn't find out how to automate it with kubectl patch, since in all my attempts it complains about '\n' characters in the json value... Still playing with it.

@phlogistonjohn

2021-03-21 23:29 UTC, obnoxxx commented
@phlogistonjohn  - I figured it out. Now the patching of coredns works (probably it's possible more elegantly), and the joining and ad-member test work!

2021-03-22 15:10 UTC, phlogistonjohn requested changes
Looks awesome, but I do see one tiny issue I think we should fix as it could be confusing in the future. Thanks!

2021-03-22 15:10 UTC, phlogistonjohn commented on tests/files/samba-ad-server-deployment.yml
> +        # Pointing to locally built image,
Comment doesn't seem right to me.

2021-03-22 15:11 UTC, phlogistonjohn commented
> I figured it out. Now the patching of coredns works (probably it's possible more elegantly), and the joining and ad-member test work!

I spent some time on last friday looking for such a more elegant way, and I didn't find one, so this is pretty fine IMO.

2021-03-22 15:44 UTC, obnoxxx commented on tests/files/samba-ad-server-deployment.yml
> +        # Pointing to locally built image,
correct. fixed :-)

2021-03-22 17:06 UTC, merged